[workspace]
members = [
  "daemon-client",
  "daemon-process",
  "daemon-server-core",
  "seeker-hook"
]
resolver = "3"

[workspace.dependencies]
seeker-daemon-server-core = {path = "daemon-server-core"}
tokio = { version = "1.47.1", features = ["full"] }
