[package]
name = "seeker-hook"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = {workspace = true}
seeker-daemon-client = {workspace = true}
tokio = {workspace = true}

[dev-dependencies]
tempfile = "3.20.0"
