[package]
name = "seeker-hook"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.20.2"
seeker-daemon-client = {workspace = true}
tokio = {workspace = true}
seeker-env = {workspace = true}

[dev-dependencies]
tempfile = "3.20.0"
