[package]
name = "seeker-daemon-server-core"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
tokio = {workspace = true}

[features]
server = ["indexer", "api"]
indexer = []
api = []
